---
ID: "80b82701-fc9b-4fe4-904a-d4a19dd9f62c"
Parent: "0d204ce1-e205-49a8-bfc0-136968d9c2e6"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Base Themes/Components Theme/gulp/tasks/watchImg
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/80B82701FC9B4FE4904AD4A19DD9F62C.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "80b82701-fc9b-4fe4-904a-d4a19dd9f62c"
  Value: aW1wb3J0IGd1bHAgZnJvbSAnZ3VscCc7DQppbXBvcnQgc2FzcyBmcm9tICdndWxwLXNhc3MnOw0KaW1wb3J0IHdhdGNoIGZyb20gJ2d1bHAtd2F0Y2gnOw0KaW1wb3J0IGNvbG9ycyBmcm9tICdjb2xvcnMnDQovLw0KaW1wb3J0IGxvZ2luIGZyb20gJy4vbG9naW4nOw0KaW1wb3J0IGNvbmZpZyBmcm9tICcuLi9jb25maWcnOw0KaW1wb3J0IGZpbGVBY3Rpb25SZXNvbHZlciBmcm9tICcuLi91dGlsL2ZpbGVBY3Rpb25SZXNvbHZlcic7DQovLw0KDQpndWxwLnRhc2soJ3dhdGNoLWltZycsIFsnbG9naW4nXSwgKCkgPT4gew0KICAgIHZhciBjb25mID0gY29uZmlnLmltZzsNCiAgICBzZXRUaW1lb3V0KGZ1bmN0aW9uKCkgew0KICAgICAgICBjb25zb2xlLmxvZygnV2F0Y2hpbmcgSW1hZ2UgZmlsZXMgc3RhcnRlZC4uLicuZ3JlZW4pOw0KICAgIH0sIDApOw0KICAgIHJldHVybiB3YXRjaChjb25mLnBhdGgsIGZ1bmN0aW9uKGZpbGUpIHsNCiAgICAgICAgZmlsZUFjdGlvblJlc29sdmVyKGZpbGUpOw0KICAgIH0pDQp9KTsNCg0KZ3VscC50YXNrKCdpbWctd2F0Y2gnLCBbJ2xvZ2luJ10sDQogICAgZnVuY3Rpb24oKSB7DQogICAgICAgIGdsb2JhbC5pc1dhdGNoaW5nID0gdHJ1ZTsNCiAgICAgICAgZ3VscC5ydW4oJ3dhdGNoLWltZycpDQogICAgfSk=
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 650
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20181205T211026Z
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5a11ee81-e681-49af-a868-0f19e1a5ff47"
