---
ID: "19185dd4-bc11-4889-bb4a-cadca61e53fa"
Parent: "5fa72b3b-08ce-4a9f-8a2c-c02d16dc54a8"
Template: "c6dc7393-15bb-4cd7-b798-ab63e77ebac4"
Path: /sitecore/content/RR/RR/Presentation/Styles/Product Banner
BranchID: "75653e9d-3c5c-45d4-823d-1bb04474400b"
SharedFields:
- ID: "62ca1c9e-71a4-465f-835e-55bda7bb270b"
  Hint: Type
  Value: droplist
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 2650
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{49BC6FF2-E504-404B-A85D-04F9C6CF7B3A}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240329T121607Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\johan.becue@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a8db29bd-57f8-4a78-afe6-82540255a5a8"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\SCNoavXWbO
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240404T113832Z
