---
ID: "11ae8e3f-d4ff-42a0-bd62-568999b8b8e0"
Parent: "85ae9213-9a88-451c-84de-76b7f4700721"
Template: "962b53c4-f93b-4df9-9821-415c867b8903"
Path: /sitecore/media library/Themes/Wireframe/gulp/tasks/gulpUploading
SharedFields:
- ID: "06d5295c-ed2f-4a54-9bf2-26228d113318"
  Hint: __Icon
  Value: "-/media/C9B997A8E292460B83DCE3FD6EC6BC8E.ashx?h=16&thn=1&w=16"
- ID: "40e50ed9-ba07-4702-992e-a912738d32dc"
  Hint: Blob
  BlobID: "11ae8e3f-d4ff-42a0-bd62-568999b8b8e0"
  Value: aW1wb3J0IGd1bHAgZnJvbSAnZ3VscCc7DQppbXBvcnQgc2FzcyBmcm9tICdndWxwLXNhc3MnOw0KaW1wb3J0IHdhdGNoIGZyb20gJ2d1bHAtd2F0Y2gnOw0KLy8NCmltcG9ydCBsb2dpbiBmcm9tICcuL2xvZ2luJzsNCmltcG9ydCBjb25maWcgZnJvbSAnLi4vY29uZmlnJzsNCmltcG9ydCB7ZmlsZUFjdGlvblJlc29sdmVyfSBmcm9tICcuLi91dGlsL2ZpbGVBY3Rpb25SZXNvbHZlcic7DQovLw0KDQpndWxwLnRhc2soJ3VwbG9hZC1ndWxwJywgWydsb2dpbiddLCAoKSA9PiB7DQogICAgcmV0dXJuIGd1bHAuc3JjKCdndWxwLyoqLyouanMnKQ0KICAgICAgICAucGlwZShndWxwLmRlc3QoZnVuY3Rpb24oZmlsZSkgew0KICAgICAgICAgICAgZmlsZUFjdGlvblJlc29sdmVyKGZpbGUsIHRydWUpOw0KICAgICAgICAgICAgcmV0dXJuICcuLyc7DQogICAgICAgIH0pKQ0KfSk7DQpndWxwLnRhc2soJ3dhdGNoLWd1bHAnLCBbJ2xvZ2luJ10sICgpID0+IHsNCiAgICByZXR1cm4gd2F0Y2goWydndWxwLyoqLyouanMnLCAnZ3VscC8qKi8qLmpzb24nXSwgZnVuY3Rpb24oZmlsZSkgew0KICAgICAgICBmaWxlQWN0aW9uUmVzb2x2ZXIoZmlsZSk7DQogICAgfSkNCn0pOw==
- ID: "6954b7c7-2487-423f-8600-436cb3b6dc0e"
  Hint: Size
  Value: 601
- ID: "6f47a0a5-9c94-4b48-abeb-42d38def6054"
  Hint: Mime Type
  Value: "application/x-javascript"
- ID: "c06867fe-9a43-4c7d-b739-48780492d06f"
  Hint: Extension
  Value: js
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20190418T071444Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3ab1036a-5510-4eed-a232-74cb63099680"
